
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INPUT = 6;
  public static final int MENOS = 15;
  public static final int MENOR = 20;
  public static final int ELSE = 3;
  public static final int IGUAL = 18;
  public static final int WHILE = 4;
  public static final int TRUE = 12;
  public static final int IF = 2;
  public static final int ID = 27;
  public static final int NUM = 28;
  public static final int MAIS = 14;
  public static final int IGUAL_IGUAL = 19;
  public static final int TIPO_STR = 11;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIV = 17;
  public static final int TIPO_CHR = 10;
  public static final int FALSE = 13;
  public static final int MAIOR = 21;
  public static final int error = 1;
  public static final int ABRE_CHAVE = 24;
  public static final int TIPO_REAL = 9;
  public static final int PONTO_VIRGULA = 26;
  public static final int FECHA_PAR = 23;
  public static final int FOR = 5;
  public static final int OUTPUT = 7;
  public static final int FECHA_CHAVE = 25;
  public static final int TIPO_INT = 8;
  public static final int ABRE_PAR = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "INPUT",
  "OUTPUT",
  "TIPO_INT",
  "TIPO_REAL",
  "TIPO_CHR",
  "TIPO_STR",
  "TRUE",
  "FALSE",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "IGUAL",
  "IGUAL_IGUAL",
  "MENOR",
  "MAIOR",
  "ABRE_PAR",
  "FECHA_PAR",
  "ABRE_CHAVE",
  "FECHA_CHAVE",
  "PONTO_VIRGULA",
  "ID",
  "NUM"
  };
}

